name: PHP CI
on:
  push:
    branches: [ master ]
 
jobs:
  make-lint:
    runs-on: macos-latest
    name: Make lint
    steps:
      - uses: actions/checkout@v2
        
      - name: Setup PHP 
        uses: shivammathur/setup-php@v1
        with:
          # Specify the PHP version
          php-version: '7.4'
          tools: phpcs, phpunit
        
      - name: run linter
        run: make lint
      - name: install package
        run: make install
      - name: run tests
        run: make test

